// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250106104823_SeedinginitalData")]
    partial class SeedinginitalData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2025, 1, 6, 16, 18, 23, 914, DateTimeKind.Local).AddTicks(4471),
                            IsCompleted = false,
                            Title = "Sleeping"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2025, 1, 6, 16, 18, 23, 914, DateTimeKind.Local).AddTicks(4482),
                            IsCompleted = false,
                            Title = "Cooking"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2025, 1, 6, 16, 18, 23, 914, DateTimeKind.Local).AddTicks(4483),
                            IsCompleted = false,
                            Title = "Playing"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2025, 1, 6, 16, 18, 23, 914, DateTimeKind.Local).AddTicks(4484),
                            IsCompleted = false,
                            Title = "Playing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
