// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Followers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("Entities.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2025, 1, 6, 22, 57, 9, 972, DateTimeKind.Local).AddTicks(7559),
                            IsCompleted = false,
                            Title = "Sleeping"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2025, 1, 6, 22, 57, 9, 972, DateTimeKind.Local).AddTicks(7571),
                            IsCompleted = false,
                            Title = "Cooking"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2025, 1, 6, 22, 57, 9, 972, DateTimeKind.Local).AddTicks(7572),
                            IsCompleted = false,
                            Title = "Playing"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2025, 1, 6, 22, 57, 9, 972, DateTimeKind.Local).AddTicks(7574),
                            IsCompleted = false,
                            Title = "Playing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
